# Generated by Django 3.1.2 on 2021-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='foodimg',
            field=models.ImageField(blank=True, null=True, upload_to='food_img'),
        ),
    ]
